### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by zdiian** [Thetan-ILW/gucci-mania#1]
1.Hoping to add Chinese, whether it is simplified or traditional, China's music game community is very large, but they prefer to support Chinese music games

2.I'm osu mania into the pit, but I found that quaver's mods such as NLN, NSV, and custom multiples can make me have a better game experience, so I used osu's community + quaver way of playing, there are too few tutorials about this game, and because of the language relationship, I may need a long time to explore, so I think adding quaver's high customization can have a great experience
![cc8a606529bde88c87d0bea8315f60d3](https://github.com/user-attachments/assets/446bd0c9-1f68-4d9c-93d9-3c0f7d18cf6b)

3.I hope to add a custom deletion filter function, such as deleting all beatmaps in n*-n* difficulty, deleting all beatmaps with a length of more than 4 minutes, etc
This is a very portable feature for people who like to download song packs but just for a few of the songs

There's a problem
The game doesn't recognize the keybo
letter keys, but keys like "tab" and "Lshift" do, and I don't know how to map the keys to "A", "S", "L", '"; ”

The above proposal is just a small proposal for the player, making it more free for the player, and I don't know how complex these technical implementations will be

**Comment by Nimue-lua** [comment]
Game already has NLN, NSV and many other mods from Quaver, you can check the modifiers in the game.

I don't know how I would translate this game into Chinese, probably I would just let ChatGPT translate it. I would try in the next few days, and you can help me fix all the mistakes in the localization.

I don't want to make an option to delete files, use filters (Beatmap Options -> Filters) or use search filters: 
```
difficulty>25 difficulty<26 // to display only charts between 25 and 26 MSD

or

duration<100 // to display short charts
```
And for the binding keys: try to use English keyboard layout, and maybe you can tell me the keyboard name and model?

**Comment by zdiian** [comment]
I managed to see the mod and map the buttons, but I still can't find the beatmap deletion screen, can you take a screenshot of the in-game location?

I'd love to help fix localization errors, but I had no translation experience before, so if you're interested in trying it out, I'll help find enthusiasts on Chinese forums or participate in person

**Comment by Nimue-lua** [comment]
You can't delete beatmaps yet, I don't like the idea of deleting maps from other games, it might break those games. It's safer to use the in-game search to find the maps you want to play.
